name: pina_app
description: Aplicación para conectar productores y compradores de piña.

# Define la versión mínima de Dart y Flutter
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase - versiones actualizadas
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  
  # Gestión de estado
  provider: ^6.1.1
  
  # Utilidades
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # Aquí irían tus assets, fuentes, etc.